name: Build

on: [push, pull_request]

jobs:
  build-and-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: jamespfennell
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build the Docker image and push to Docker Hub
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          tags: jamespfennell/subwaydata.nyc:latest
          # Only push to Docker Hub if this workflow is a push to main
          push: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}

